language: scala
jdk:
  - oraclejdk8
node_js:
secure: "12345secure"
before_script:
  - npm install -g @angular/cli
script:
  - sbt clean coverage test && sbt coverageAggregate
  - ng build --prod
after_success:
  - sbt coveralls
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
