language: scala
jdk:
  - oraclejdk8
secure: "12345secure"
script:
  - sbt clean compile coverage test coverageReport
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
